import fs from "fs";
import path from "path";
import yaml from "js-yaml";

/**
 * Non-secret configuration, shared with the Python service via config.yaml.
 * Only the fields the HomeKit app cares about are typed here.
 */
export interface AppConfig {
  cameraName: string;
  rtspUrl: string;
  motionPort: number;
  motionTimeout: number;
  width: number;
  height: number;
  fps: number;
  maxBitrate: number; // kbit/s
}

/**
 * Pairing secrets generated by install.sh into pairing.json. Never committed.
 *   username : accessory MAC (XX:XX:XX:XX:XX:XX, locally administered)
 *   pincode  : HomeKit setup code (XXX-XX-XXX)
 *   setupID  : 4-char setup ID used in the QR code
 */
export interface Pairing {
  username: string;
  pincode: string;
  setupID: string;
}

function candidatePaths(filename: string): string[] {
  return [
    path.resolve(__dirname, "..", "..", filename), // repo root (dev)
    path.join("/opt/pi4cam", filename), // installed location
  ];
}

function firstExisting(filename: string): string {
  for (const p of candidatePaths(filename)) {
    if (fs.existsSync(p)) {
      return p;
    }
  }
  throw new Error(
    `${filename} not found (looked in: ${candidatePaths(filename).join(", ")})`,
  );
}

/**
 * The homekit/ working directory (holds pairing.json + the persist/ store).
 * Installed at /opt/pi4cam/homekit; falls back to the repo's homekit/ in dev.
 */
export function homekitDir(): string {
  const installed = "/opt/pi4cam/homekit";
  if (fs.existsSync(installed)) {
    return installed;
  }
  return path.resolve(__dirname, "..");
}

export function loadConfig(): AppConfig {
  const raw = yaml.load(fs.readFileSync(firstExisting("config.yaml"), "utf8")) as
    | Record<string, any>
    | undefined;
  const cfg = raw ?? {};
  const camera = cfg.camera ?? {};
  const rtsp = cfg.rtsp ?? {};
  const homekit = cfg.homekit ?? {};

  const rtspPort = Number(rtsp.port ?? 8554);

  return {
    cameraName: String(homekit.camera_name ?? "Pi Camera"),
    rtspUrl: `rtsp://127.0.0.1:${rtspPort}/camera`,
    motionPort: Number(homekit.motion_port ?? 8989),
    motionTimeout: Number(homekit.motion_timeout ?? 10),
    width: Number(camera.width ?? 1920),
    height: Number(camera.height ?? 1080),
    fps: Number(camera.fps ?? 30),
    // config.yaml stores bitrate in bit/s; HomeKit wants kbit/s.
    maxBitrate: Math.round(Number(camera.bitrate ?? 4_000_000) / 1000),
  };
}

export function loadPairing(): Pairing {
  const p = path.join(homekitDir(), "pairing.json");
  if (!fs.existsSync(p)) {
    throw new Error(
      `${p} not found — run install.sh to generate the pairing secrets`,
    );
  }
  const data = JSON.parse(fs.readFileSync(p, "utf8")) as Partial<Pairing>;
  if (!data.username || !data.pincode || !data.setupID) {
    throw new Error(`${p} is missing username/pincode/setupID`);
  }
  return data as Pairing;
}
