/**
 * WebRTC media-engine abstraction for the new-HKSV live path (#59).
 *
 * The HAP layer (webrtc-sessions.ts) never talks to go2rtc directly — it
 * sees this interface, so the engine can be swapped (or faked in tests)
 * without touching protocol code.
 *
 * Go2RtcEngine speaks the patched go2rtc's WebSocket protocol
 * (scripts/go2rtc-solicit.patch): per §5 of the spec the ACCESSORY
 * generates the SDP offer, which stock go2rtc cannot do for a consumer.
 *
 *   us     → {"type":"webrtc/solicit"}            (?src=<stream> in URL)
 *   go2rtc → {"type":"webrtc/offer","value":sdp}  (complete offer, ICE inline)
 *   us     → {"type":"webrtc/answer","value":sdp} (controller's answer)
 *   go2rtc → {"type":"error","value":…}           (only on failure)
 */
import WebSocket from "ws";

export interface EngineSession {
  /** RFC 8866 SDP offer generated by the media engine (accessory side). */
  readonly offer: string;
  /** Forward the controller's SDP answer. Resolves once handed to the
   *  engine; engine-side failures surface through onClosed. */
  provideAnswer(sdpAnswer: string): Promise<void>;
  /** Tear the media session down. Idempotent. */
  close(): void;
  /** Fired when the engine drops the session (error or remote close). */
  onClosed?: (reason: string) => void;
}

export interface WebRtcEngine {
  /** Open a media session for a stream source and return its SDP offer. */
  solicit(src: string): Promise<EngineSession>;
}

const OFFER_TIMEOUT_MS = 10_000;

class Go2RtcSession implements EngineSession {
  onClosed?: (reason: string) => void;
  private closed = false;

  constructor(
    private readonly socket: WebSocket,
    readonly offer: string,
  ) {
    socket.on("message", (data) => {
      // After the offer, only candidates/errors arrive. Candidates inside
      // the complete offer are enough for the LAN case — trickle handling
      // is the documented plan B if field latency demands it.
      try {
        const msg = JSON.parse(String(data));
        if (msg.type === "error") {
          this.dispose(`go2rtc error: ${msg.value}`);
        }
      } catch {
        /* non-JSON frames are ignored */
      }
    });
    socket.on("close", () => this.dispose("engine socket closed"));
    socket.on("error", (err) => this.dispose(`engine socket error: ${err.message}`));
  }

  async provideAnswer(sdpAnswer: string): Promise<void> {
    if (this.closed) throw new Error("session closed");
    this.socket.send(JSON.stringify({ type: "webrtc/answer", value: sdpAnswer }));
  }

  close(): void {
    this.dispose("closed by HAP layer");
  }

  private dispose(reason: string): void {
    if (this.closed) return;
    this.closed = true;
    try {
      this.socket.close();
    } catch {
      /* already closing */
    }
    this.onClosed?.(reason);
  }
}

export class Go2RtcEngine implements WebRtcEngine {
  /** @param apiUrl go2rtc API base, e.g. "http://127.0.0.1:1984" */
  constructor(private readonly apiUrl: string) {}

  solicit(src: string): Promise<EngineSession> {
    const wsUrl =
      this.apiUrl.replace(/^http/, "ws").replace(/\/$/, "") +
      `/api/ws?src=${encodeURIComponent(src)}`;
    return new Promise((resolve, reject) => {
      const socket = new WebSocket(wsUrl);
      const timer = setTimeout(() => {
        socket.close();
        reject(new Error(`go2rtc offer timeout (${OFFER_TIMEOUT_MS} ms) for ${src}`));
      }, OFFER_TIMEOUT_MS);

      socket.on("open", () => {
        socket.send(JSON.stringify({ type: "webrtc/solicit" }));
      });
      socket.on("error", (err) => {
        clearTimeout(timer);
        reject(new Error(`go2rtc unreachable at ${wsUrl}: ${err.message}`));
      });
      socket.once("message", function waitOffer(this: WebSocket, data) {
        let msg: { type?: string; value?: string };
        try {
          msg = JSON.parse(String(data));
        } catch {
          msg = {};
        }
        if (msg.type === "webrtc/offer" && typeof msg.value === "string") {
          clearTimeout(timer);
          resolve(new Go2RtcSession(socket, msg.value));
        } else if (msg.type === "error") {
          clearTimeout(timer);
          socket.close();
          reject(new Error(`go2rtc: ${msg.value}`));
        } else {
          // e.g. an early webrtc/candidate — keep waiting for the offer
          socket.once("message", waitOffer);
        }
      });
    });
  }
}
